<?php
// +----------------------------------------------------------------------
// | 中犇单商户
// +----------------------------------------------------------------------
// | Copyright (c) 2019-2021 中犇科技 All rights reserved.
// +----------------------------------------------------------------------


/**
 * 菜单信息
 */
return [
    [
        'title' => lang('商城'),
        'icon' => 'fa fa-fw fa-cubes',
        'url_value' => 'goods/index/index',
        'url_target' => '_self',
        'online_hide' => 0,
        'sort' => 1,
        'status' => 1,
        'child' => [
            [
                'title' => lang('商品管理'),
                'icon' => 'fa fa-fw fa-folder-open-o',
                'url_value' => '',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 1,
                'status' => 1,
                'child' => [
                    [
                        'title' => lang('商品列表'),
                        'icon' => 'fa fa-fw fa-list',
                        'url_value' => 'goods/index/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 1,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('评论编辑'),
                                'icon' => '',
                                'url_value' => 'goods/comment/edit',
                                'url_target' => '_self',
                                'online_hide' => 1,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => '评论启用/禁用',
                                'icon' => '',
                                'url_value' => 'goods/comment/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 1,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('评论列表'),
                                'icon' => '',
                                'url_value' => 'goods/comment/index',
                                'url_target' => '_self',
                                'online_hide' => 1,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/index/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/index/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 5,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('启用'),
                                'icon' => '',
                                'url_value' => 'goods/index/enable',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 6,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('禁用'),
                                'icon' => '',
                                'url_value' => 'goods/index/disable',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 7,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/index/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 8,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('商品分类'),
                        'icon' => 'fa fa-fw fa-list',
                        'url_value' => 'goods/category/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 2,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/category/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/category/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/category/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/category/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('规格属性'),
                        'icon' => 'fa fa-fw fa-gg',
                        'url_value' => 'goods/type/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 3,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/type/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/type/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/type/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/type/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('品牌列表'),
                        'icon' => 'fa fa-fw fa-gg-circle',
                        'url_value' => 'goods/brand/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 4,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/brand/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/brand/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/brand/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/brand/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title' => lang('订单管理'),
                'icon' => 'fa fa-fw fa-list',
                'url_value' => '',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 2,
                'status' => 1,
                'child' => [
                    [
                        'title' => lang('订单列表'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 1,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('查看详情'),
                                'icon' => '',
                                'url_value' => 'goods/order/detail',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/order/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/order/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/order/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('秒杀订单'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/seckill',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 2,
                        'status' => 1,
                    ],
                    [
                        'title' => lang('拼团订单'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/group',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 3,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('立即满团'),
                                'icon' => '',
                                'url_value' => 'goods/order/add_robot_to_group',
                                'url_target' => '_self',
                                'online_hide' => 1,
                                'sort' => 1,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('预售订单'),
                        'icon' => 'fa fa-fw fa-list-alt',
                        'url_value' => 'goods/order/presell',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 7,
                        'status' => 1,
                    ],
                    [
                        'title' => lang('订单物流'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/express',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 4,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('添加物流'),
                                'icon' => '',
                                'url_value' => 'goods/order/express_add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除物流信息'),
                                'icon' => '',
                                'url_value' => 'goods/order/express_del',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('订单售后'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/refund',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 5,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('订单售后物流'),
                                'icon' => '',
                                'url_value' => 'goods/order/refund_express',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('售后详情'),
                                'icon' => '',
                                'url_value' => 'goods/order/refund_detail',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('退货通过'),
                                'icon' => '',
                                'url_value' => 'goods/order/refund_sure',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('退货驳回'),
                                'icon' => '',
                                'url_value' => 'goods/order/refund_del',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('订单提醒'),
                        'icon' => 'fa fa-fw fa-list-ol',
                        'url_value' => 'goods/order/remind',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 6,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('标记已读'),
                                'icon' => '',
                                'url_value' => 'goods/order/remind_read',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('提醒删除'),
                                'icon' => '',
                                'url_value' => 'goods/order/remind_del',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title' => lang('供应商管理'),
                'icon' => 'fa fa-fw fa-female',
                'url_value' => '',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
                'child' => [
                    [
                        'title' => lang('供应商列表'),
                        'icon' => 'fa fa-fw fa-female',
                        'url_value' => 'goods/sender/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 4,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/sender/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/sender/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/sender/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/sender/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                ]
            ],
            [
                'title' => lang('活动管理'),
                'icon' => 'fa fa-fw fa-cny',
                'url_value' => '',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 3,
                'status' => 1,
                'child' => [
                    [
                        'title' => lang('秒杀活动'),
                        'icon' => 'fa fa-fw fa-building',
                        'url_value' => 'goods/seckill/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 1,
                        'status' => 1,
                        'child'=>[
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/seckill/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/seckill/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/seckill/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/seckill/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ]
                    ],
                    [
                        'title' => lang('拼团活动'),
                        'icon' => 'fa fa-fw fa-building',
                        'url_value' => 'goods/group/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 2,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/group/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/group/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/group/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/group/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('预售活动'),
                        'icon' => 'fa fa-fw fa-apple',
                        'url_value' => 'goods/pre_sell/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 3,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/pre_sell/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/pre_sell/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/pre_sell/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/pre_sell/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('活动商品'),
                        'icon' => 'fa fa-fw fa-building',
                        'url_value' => 'goods/activity_details/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 4,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('获取商品数据'),
                                'icon' => '',
                                'url_value' => 'goods/activity_details/getgoodsbycid',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/activity_details/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/activity_details/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/activity_details/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                ],
            ],
            [
                'title' => lang('配送管理'),
                'icon' => 'fa fa-fw fa-plane',
                'url_value' => '',
                'url_target' => '_self',
                'online_hide' => 0,
                'sort' => 4,
                'status' => 1,
                'child' => [
                    [
                        'title' => lang('快递公司'),
                        'icon' => 'fa fa-fw fa-building',
                        'url_value' => 'goods/express_company/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 1,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('查看快递编码'),
                                'icon' => '',
                                'url_value' => 'goods/express_company/express_code',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/express_company/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/express_company/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/express_company/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/express_company/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 5,
                                'status' => 1,
                            ],
                        ],
                    ],
                    [
                        'title' => lang('运费模板'),
                        'icon' => 'fa fa-fw fa-cab',
                        'url_value' => 'goods/freight/index',
                        'url_target' => '_self',
                        'online_hide' => 0,
                        'sort' => 2,
                        'status' => 1,
                        'child' => [
                            [
                                'title' => lang('新增'),
                                'icon' => '',
                                'url_value' => 'goods/freight/add',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 1,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('编辑'),
                                'icon' => '',
                                'url_value' => 'goods/freight/edit',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 2,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('删除'),
                                'icon' => '',
                                'url_value' => 'goods/freight/delete',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 3,
                                'status' => 1,
                            ],
                            [
                                'title' => lang('设置状态'),
                                'icon' => '',
                                'url_value' => 'goods/freight/setstatus',
                                'url_target' => '_self',
                                'online_hide' => 0,
                                'sort' => 4,
                                'status' => 1,
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
